FROM node:lts-alpine
WORKDIR /app
RUN npm install cd -g @vue/cli

# docker build -t vueapp -f Dockerfile-creare-app .
# docker run -X -v ${PWD}:/app --name vueapp vueapp
# docker exec -it vueapp vue create my-projectp
# sudo chown -R $USER:$(id -gn $USER) ./*